server:
  port: 9014
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: langchain4j-14-chat-mcp

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${BAILIAN_API_KEY}
        model-name: qwen3-max-preview
      chat-model:
        api-key: ${BAILIAN_API_KEY}
        model-name: qwen3-max-preview

logging:
  level:
    dev:
      langchain4j: DEBUG